Import Libaries

In [1]:
import pandas as pd
import numpy as np

Load Dataset

In [2]:
#reading the dataset 
r_cols=['user_id','movie_id','rating','unix_timestamp']
ratings=pd.read_csv('ml-100k/u.data',sep='\t',names=r_cols,encoding='latin-1')

In [3]:
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [4]:
n_users=ratings.user_id.unique().shape[0]
n_items=ratings.movie_id.unique().shape[0]

In [5]:
print('The Number of User : ',n_users)
print('The Number of n_items : ',n_items)

The Number of User :  943
The Number of n_items :  1682

Create Pivot Table for User & Movie Basedon Ratings

In [6]:
datama=ratings.pivot_table(index='user_id',columns='movie_id',values='rating')

In [7]:
datama

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#replace with NaN with 0
data_matrix=datama.replace(np.nan,0)

In [9]:
data_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Find Cosine Similarity for User & Item

In [10]:
from sklearn.metrics.pairwise import pairwise_distances

In [11]:
user_similarity=pairwise_distances(data_matrix,metric='cosine')
item_similarity=pairwise_distances(data_matrix.T,metric='cosine')

In [12]:
user_similarity

array([[2.44249065e-15, 8.33069016e-01, 9.52540457e-01, ...,
        8.51383057e-01, 8.20492117e-01, 6.01825261e-01],
       [8.33069016e-01, 3.33066907e-16, 8.89408675e-01, ...,
        8.38515222e-01, 8.27732187e-01, 8.94202122e-01],
       [9.52540457e-01, 8.89408675e-01, 0.00000000e+00, ...,
        8.98757435e-01, 8.66583851e-01, 9.73444131e-01],
       ...,
       [8.51383057e-01, 8.38515222e-01, 8.98757435e-01, ...,
        0.00000000e+00, 8.98358201e-01, 9.04880419e-01],
       [8.20492117e-01, 8.27732187e-01, 8.66583851e-01, ...,
        8.98358201e-01, 1.11022302e-16, 8.17535338e-01],
       [6.01825261e-01, 8.94202122e-01, 9.73444131e-01, ...,
        9.04880419e-01, 8.17535338e-01, 0.00000000e+00]])

Using formula for User & Item we are Calculating the score value

In [13]:
def predict(ratings,similarity,type='user'):
    if type=='user':
        mean_user_rating=ratings.mean(axis=1).values
        #we use np.newaxis so that mean_user_ratings has same format as ratings
        ratings_diff=(ratings-mean_user_rating[:,np.newaxis])
        pred=mean_user_rating[:,np.newaxis]+similarity.dot(ratings_diff)/np.array([np.abs(similarity).sum(axis=1)]).T
    elif type=='item':
        pred=ratings.dot(similarity)/np.array([np.abs(similarity).sum(axis=1)])

    return pred

In [14]:
#Prediction Table

user_prediction=predict(data_matrix,user_similarity,type='user')
item_prediction=predict(data_matrix,item_similarity,type='item')

In [15]:
user_prediction

array([[ 2.06532606,  0.73430275,  0.62992381, ...,  0.39359041,
         0.39304874,  0.3927712 ],
       [ 1.76308836,  0.38404019,  0.19617889, ..., -0.08837789,
        -0.0869183 , -0.08671183],
       [ 1.79590398,  0.32904733,  0.15882885, ..., -0.13699223,
        -0.13496852, -0.13476488],
       ...,
       [ 1.59151513,  0.27526889,  0.10219534, ..., -0.16735162,
        -0.16657451, -0.16641377],
       [ 1.81036267,  0.40479877,  0.27545013, ..., -0.00907358,
        -0.00846587, -0.00804858],
       [ 1.8384313 ,  0.47964837,  0.38496292, ...,  0.14686675,
         0.14629808,  0.14641455]])

As Per User Based Filtering , First have to find Similarity between the input users & others

In [16]:
# 1. Select Input User

input_user=34

In [17]:
# 2. Convert the user_sim table into DataFrame

user_sim_table=pd.DataFrame(user_similarity)

In [18]:
# 3. Find Similarity User for 34 using Cosine Table 
similar_input_user=user_sim_table[input_user].sort_values(ascending=True).head(5).index

In [19]:
similar_input_user   #get the similar user index value

Index([34, 450, 852, 811, 509], dtype='int64')

In [20]:
# 4.convert into list

similar_input_user=list(similar_input_user)

In [21]:
# 5. Using similar_user_input , Can select movie_id from ratings table

similar_user_movieid_list=[]
for sim_user in similar_input_user:
    sim=list(ratings[ratings['user_id']==sim_user]['movie_id'])
    similar_user_movieid_list.append(sim)

In [22]:
# 6.Convert all the list as Single 

import itertools
similar_user_movieid_single_list=list(itertools.chain.from_iterable(similar_user_movieid_list))

In [23]:
len(similar_user_movieid_list)

5

In [24]:
# 7.Unique moiveid from the list

unique_movieid_similar_user=set(similar_user_movieid_single_list)

In [25]:
len(unique_movieid_similar_user)

590

In [26]:
# 8.Input User watched movie list 

input_user_watched_movieid=list(ratings[ratings['user_id']==input_user]['movie_id'].values)

In [27]:
len(input_user_watched_movieid)

20

In [28]:
# 9. Create a list which should have recomm moie_id to the input user

recom=[]
for per_id in unique_movieid_similar_user:
    if(per_id in input_user_watched_movieid):
        pass
    else:
        recom.append(per_id)

In [29]:
len(recom)

570

In [30]:
sorted(recom)

[1,
 2,
 3,
 4,
 7,
 10,
 11,
 12,
 13,
 15,
 22,
 23,
 25,
 26,
 28,
 29,
 33,
 35,
 38,
 39,
 43,
 44,
 47,
 49,
 50,
 51,
 54,
 56,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 73,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 109,
 110,
 111,
 112,
 114,
 117,
 118,
 121,
 122,
 123,
 125,
 126,
 127,
 131,
 132,
 133,
 134,
 135,
 136,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 151,
 152,
 153,
 154,
 155,
 157,
 158,
 161,
 162,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 237,
 238,
 239,
 241,
 243,
 250,
 252,
 254,
 257,
 258,
 260,
 264,
 265,
 266,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 277,
 278,
 280,
 281,
 282,
 283,
 284,
 287,
 290,
 300,
 301,
 302,
 304,
 305,
 307,
 308,
 309,
 311,
 313,
 315,
 316,
 318,
 319,
 321,
 322,
 323,
 326,
 328,
 336,
 338,
 340,
 343,
 345,
 347,
 354,
 356,
 357,
 358,
 366,
 367,
 371,
 372,
 373,
 378,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 392,
 393,
 395,
 396,
 399,
 400,
 401,
 402,
 403,
 405,
 407,
 408,
 414,
 415,
 416,
 417,
 418,
 419,
 421,
 422,
 423,
 427,
 428,
 430,
 431,
 432,
 433,
 434,
 435,
 443,
 448,
 451,
 455,
 457,
 462,
 465,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 509,
 510,
 511,
 514,
 515,
 516,
 518,
 519,
 520,
 521,
 523,
 525,
 526,
 527,
 528,
 530,
 535,
 546,
 549,
 550,
 553,
 557,
 558,
 559,
 561,
 566,
 568,
 570,
 571,
 582,
 583,
 584,
 588,
 589,
 591,
 597,
 601,
 602,
 603,
 604,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 616,
 618,
 619,
 620,
 622,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 637,
 642,
 647,
 648,
 650,
 651,
 654,
 655,
 657,
 659,
 660,
 661,
 662,
 663,
 671,
 673,
 678,
 679,
 680,
 681,
 685,
 686,
 687,
 689,
 692,
 693,
 696,
 699,
 700,
 702,
 704,
 705,
 707,
 708,
 709,
 710,
 712,
 713,
 714,
 715,
 716,
 717,
 722,
 723,
 724,
 725,
 727,
 728,
 729,
 731,
 732,
 734,
 735,
 736,
 739,
 741,
 742,
 747,
 748,
 749,
 750,
 751,
 754,
 756,
 761,
 762,
 765,
 771,
 774,
 775,
 776,
 778,
 781,
 783,
 785,
 790,
 792,
 794,
 795,
 801,
 807,
 812,
 815,
 820,
 821,
 823,
 825,
 826,
 827,
 832,
 837,
 840,
 841,
 842,
 845,
 846,
 847,
 865,
 866,
 869,
 873,
 878,
 879,
 892,
 895,
 900,
 901,
 902,
 904,
 905,
 908,
 921,
 923,
 926,
 928,
 930,
 934,
 936,
 939,
 940,
 942,
 951,
 956,
 965,
 966,
 967,
 968,
 969,
 988,
 1020,
 1028,
 1030,
 1033,
 1036,
 1037,
 1039,
 1041,
 1044,
 1047,
 1048,
 1050,
 1052,
 1053,
 1054,
 1061,
 1091,
 1092,
 1107,
 1112,
 1115,
 1116,
 1119,
 1126,
 1135,
 1140,
 1147,
 1152,
 1153,
 1160,
 1163,
 1172,
 1184,
 1192,
 1197,
 1203,
 1208,
 1212,
 1220,
 1221,
 1222,
 1226,
 1248,
 1249,
 1261,
 1263,
 1269,
 1271,
 1282,
 1284,
 1286,
 1297,
 1303,
 1311,
 1401,
 1402,
 1421,
 1425,
 1435,
 1441,
 1444,
 1446,
 1479,
 1480,
 1490,
 1518,
 1521,
 1603,
 1615]

In [31]:
#cross checking
sorted(unique_movieid_similar_user)

[1,
 2,
 3,
 4,
 7,
 10,
 11,
 12,
 13,
 15,
 22,
 23,
 25,
 26,
 28,
 29,
 33,
 35,
 38,
 39,
 43,
 44,
 47,
 49,
 50,
 51,
 54,
 56,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 73,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 109,
 110,
 111,
 112,
 114,
 117,
 118,
 121,
 122,
 123,
 125,
 126,
 127,
 131,
 132,
 133,
 134,
 135,
 136,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 151,
 152,
 153,
 154,
 155,
 157,
 158,
 161,
 162,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 237,
 238,
 239,
 241,
 242,
 243,
 245,
 250,
 252,
 254,
 257,
 258,
 259,
 260,
 264,
 265,
 266,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 277,
 278,
 280,
 281,
 282,
 283,
 284,
 286,
 287,
 288,
 289,
 290,
 292,
 294,
 299,
 300,
 301,
 302,
 304,
 305,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 315,
 316,
 318,
 319,
 321,
 322,
 323,
 324,
 326,
 328,
 329,
 332,
 336,
 338,
 340,
 343,
 345,
 347,
 354,
 356,
 357,
 358,
 366,
 367,
 371,
 372,
 373,
 378,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 392,
 393,
 395,
 396,
 399,
 400,
 401,
 402,
 403,
 405,
 407,
 408,
 414,
 415,
 416,
 417,
 418,
 419,
 421,
 422,
 423,
 427,
 428,
 430,
 431,
 432,
 433,
 434,
 435,
 443,
 448,
 451,
 455,
 457,
 462,
 465,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 509,
 510,
 511,
 514,
 515,
 516,
 518,
 519,
 520,
 521,
 523,
 525,
 526,
 527,
 528,
 530,
 535,
 546,
 549,
 550,
 553,
 557,
 558,
 559,
 561,
 566,
 568,
 570,
 571,
 582,
 583,
 584,
 588,
 589,
 591,
 597,
 601,
 602,
 603,
 604,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 616,
 618,
 619,
 620,
 622,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 637,
 642,
 647,
 648,
 650,
 651,
 654,
 655,
 657,
 659,
 660,
 661,
 662,
 663,
 671,
 673,
 678,
 679,
 680,
 681,
 685,
 686,
 687,
 689,
 690,
 692,
 693,
 696,
 699,
 700,
 702,
 704,
 705,
 707,
 708,
 709,
 710,
 712,
 713,
 714,
 715,
 716,
 717,
 722,
 723,
 724,
 725,
 727,
 728,
 729,
 731,
 732,
 734,
 735,
 736,
 739,
 741,
 742,
 747,
 748,
 749,
 750,
 751,
 754,
 756,
 761,
 762,
 765,
 771,
 774,
 775,
 776,
 778,
 781,
 783,
 785,
 790,
 792,
 794,
 795,
 801,
 807,
 812,
 815,
 820,
 821,
 823,
 825,
 826,
 827,
 832,
 837,
 840,
 841,
 842,
 845,
 846,
 847,
 865,
 866,
 869,
 873,
 878,
 879,
 892,
 895,
 898,
 899,
 900,
 901,
 902,
 904,
 905,
 908,
 921,
 923,
 926,
 928,
 930,
 934,
 936,
 939,
 940,
 942,
 951,
 956,
 965,
 966,
 967,
 968,
 969,
 988,
 990,
 991,
 1020,
 1024,
 1028,
 1030,
 1033,
 1036,
 1037,
 1039,
 1041,
 1044,
 1047,
 1048,
 1050,
 1052,
 1053,
 1054,
 1061,
 1091,
 1092,
 1107,
 1112,
 1115,
 1116,
 1119,
 1126,
 1135,
 1140,
 1147,
 1152,
 1153,
 1160,
 1163,
 1172,
 1184,
 1192,
 1197,
 1203,
 1208,
 1212,
 1220,
 1221,
 1222,
 1226,
 1248,
 1249,
 1261,
 1263,
 1269,
 1271,
 1282,
 1284,
 1286,
 1297,
 1303,
 1311,
 1401,
 1402,
 1421,
 1425,
 1435,
 1441,
 1444,
 1446,
 1479,
 1480,
 1490,
 1518,
 1521,
 1603,
 1615]

In [32]:
#cross Cjecking
sorted(input_user_watched_movieid)

[np.int64(242),
 np.int64(245),
 np.int64(259),
 np.int64(286),
 np.int64(288),
 np.int64(289),
 np.int64(292),
 np.int64(294),
 np.int64(299),
 np.int64(310),
 np.int64(312),
 np.int64(324),
 np.int64(329),
 np.int64(332),
 np.int64(690),
 np.int64(898),
 np.int64(899),
 np.int64(990),
 np.int64(991),
 np.int64(1024)]

In [33]:
# Checking the Common Movie list

list(set(unique_movieid_similar_user)&set(input_user_watched_movieid))

[np.int64(1024),
 np.int64(898),
 np.int64(259),
 np.int64(899),
 np.int64(286),
 np.int64(288),
 np.int64(289),
 np.int64(292),
 np.int64(294),
 np.int64(299),
 np.int64(690),
 np.int64(310),
 np.int64(312),
 np.int64(324),
 np.int64(329),
 np.int64(332),
 np.int64(990),
 np.int64(991),
 np.int64(242),
 np.int64(245)]

In [34]:
user_pred=pd.DataFrame(user_prediction)

user_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,2.065326,0.734303,0.629924,1.010669,0.640686,0.476150,1.784569,1.163032,1.513350,0.704478,...,0.394041,0.394434,0.393981,0.392972,0.393344,0.392272,0.394909,0.393590,0.393049,0.392771
1,1.763088,0.384040,0.196179,0.731538,0.225643,0.003892,1.493597,0.876153,1.108467,0.261991,...,-0.086942,-0.085491,-0.087137,-0.088158,-0.087298,-0.089288,-0.087468,-0.088378,-0.086918,-0.086712
2,1.795904,0.329047,0.158829,0.684154,0.173277,-0.035621,1.488230,0.835769,1.135426,0.236383,...,-0.134795,-0.133537,-0.135543,-0.136438,-0.135041,-0.137611,-0.136374,-0.136992,-0.134969,-0.134765
3,1.729951,0.293913,0.127741,0.644932,0.142143,-0.062261,1.437010,0.796249,1.096663,0.211789,...,-0.161413,-0.160220,-0.161542,-0.162586,-0.161634,-0.163877,-0.162283,-0.163080,-0.161442,-0.161248
4,1.796651,0.454474,0.354422,0.763130,0.359539,0.195987,1.547370,0.908904,1.292027,0.437954,...,0.101762,0.102405,0.101923,0.100839,0.101711,0.099951,0.102515,0.101233,0.101075,0.101201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,1.676950,0.346339,0.177518,0.689906,0.199740,0.003297,1.429565,0.830905,1.070986,0.262183,...,-0.092434,-0.091197,-0.092851,-0.093801,-0.092953,-0.094539,-0.092217,-0.093378,-0.092686,-0.092423
939,1.822346,0.419125,0.286430,0.715605,0.294442,0.106633,1.514591,0.853050,1.195304,0.359260,...,0.014060,0.014688,0.014123,0.013060,0.013669,0.011978,0.014065,0.013021,0.013639,0.013796
940,1.591515,0.275269,0.102195,0.624383,0.133762,-0.069553,1.320734,0.765529,1.035088,0.192697,...,-0.166179,-0.164981,-0.166278,-0.167392,-0.166679,-0.168486,-0.166217,-0.167352,-0.166575,-0.166414
941,1.810363,0.404799,0.275450,0.726616,0.281316,0.087068,1.550310,0.850057,1.205745,0.342987,...,-0.008362,-0.007757,-0.008225,-0.009218,-0.008232,-0.010138,-0.008009,-0.009074,-0.008466,-0.008049
942,1.838431,0.479648,0.384963,0.780521,0.388442,0.240998,1.564232,0.946704,1.289865,0.487383,...,0.147027,0.148208,0.147193,0.146199,0.146916,0.145539,0.148194,0.146867,0.146298,0.146415

In [35]:
user_pred_Trans=user_pred.T

In [36]:
user_pred_Trans

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,2.065326,1.763088,1.795904,1.729951,1.796651,1.996889,2.466055,1.693486,1.681165,2.021688,...,1.924844,1.619096,1.891812,1.696368,1.717658,1.676950,1.822346,1.591515,1.810363,1.838431
1,0.734303,0.384040,0.329047,0.293913,0.454474,0.651172,1.099186,0.296285,0.279528,0.650911,...,0.552456,0.311680,0.550513,0.322611,0.431368,0.346339,0.419125,0.275269,0.404799,0.479648
2,0.629924,0.196179,0.158829,0.127741,0.354422,0.528276,1.016489,0.195398,0.121887,0.530669,...,0.451194,0.140613,0.354913,0.144344,0.247851,0.177518,0.286430,0.102195,0.275450,0.384963
3,1.010669,0.731538,0.684154,0.644932,0.763130,0.921054,1.362861,0.612075,0.616094,0.916215,...,0.834176,0.661829,0.893214,0.662304,0.783208,0.689906,0.715605,0.624383,0.726616,0.780521
4,0.640686,0.225643,0.173277,0.142143,0.359539,0.537388,1.006458,0.198638,0.136368,0.531720,...,0.455212,0.166992,0.398759,0.167841,0.283796,0.199740,0.294442,0.133762,0.281316,0.388442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.392272,-0.089288,-0.137611,-0.163877,0.099951,0.259848,0.764340,-0.072866,-0.163505,0.263527,...,0.185602,-0.128949,0.095681,-0.143177,-0.009425,-0.094539,0.011978,-0.168486,-0.010138,0.145539
1678,0.394909,-0.087468,-0.136374,-0.162283,0.102515,0.262375,0.766967,-0.070435,-0.161425,0.266037,...,0.188059,-0.126624,0.097792,-0.141018,-0.007085,-0.092217,0.014065,-0.166217,-0.008009,0.148194
1679,0.393590,-0.088378,-0.136992,-0.163080,0.101233,0.261111,0.765654,-0.071651,-0.162465,0.264782,...,0.186831,-0.127786,0.096736,-0.142097,-0.008255,-0.093378,0.013021,-0.167352,-0.009074,0.146867
1680,0.393049,-0.086918,-0.134969,-0.161442,0.101075,0.261061,0.764983,-0.071744,-0.161396,0.264589,...,0.186850,-0.127045,0.097826,-0.140977,-0.007621,-0.092686,0.013639,-0.166575,-0.008466,0.146298
1681,0.392771,-0.086712,-0.134765,-0.161248,0.101201,0.261089,0.765165,-0.071357,-0.161430,0.264781,...,0.186858,-0.126812,0.097654,-0.140965,-0.007369,-0.092423,0.013796,-0.166414,-0.008049,0.146415

In [37]:
user_pred_Trans[34]

0       1.740469
1       0.283366
2       0.114987
3       0.645096
4       0.127844
          ...
1677   -0.183977
1678   -0.182367
1679   -0.183172
1680   -0.181400
1681   -0.181306
Name: 34, Length: 1682, dtype: float64

In [38]:
gg=user_pred_Trans

In [39]:
g=pd.DataFrame(gg)

In [40]:
g

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,2.065326,1.763088,1.795904,1.729951,1.796651,1.996889,2.466055,1.693486,1.681165,2.021688,...,1.924844,1.619096,1.891812,1.696368,1.717658,1.676950,1.822346,1.591515,1.810363,1.838431
1,0.734303,0.384040,0.329047,0.293913,0.454474,0.651172,1.099186,0.296285,0.279528,0.650911,...,0.552456,0.311680,0.550513,0.322611,0.431368,0.346339,0.419125,0.275269,0.404799,0.479648
2,0.629924,0.196179,0.158829,0.127741,0.354422,0.528276,1.016489,0.195398,0.121887,0.530669,...,0.451194,0.140613,0.354913,0.144344,0.247851,0.177518,0.286430,0.102195,0.275450,0.384963
3,1.010669,0.731538,0.684154,0.644932,0.763130,0.921054,1.362861,0.612075,0.616094,0.916215,...,0.834176,0.661829,0.893214,0.662304,0.783208,0.689906,0.715605,0.624383,0.726616,0.780521
4,0.640686,0.225643,0.173277,0.142143,0.359539,0.537388,1.006458,0.198638,0.136368,0.531720,...,0.455212,0.166992,0.398759,0.167841,0.283796,0.199740,0.294442,0.133762,0.281316,0.388442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.392272,-0.089288,-0.137611,-0.163877,0.099951,0.259848,0.764340,-0.072866,-0.163505,0.263527,...,0.185602,-0.128949,0.095681,-0.143177,-0.009425,-0.094539,0.011978,-0.168486,-0.010138,0.145539
1678,0.394909,-0.087468,-0.136374,-0.162283,0.102515,0.262375,0.766967,-0.070435,-0.161425,0.266037,...,0.188059,-0.126624,0.097792,-0.141018,-0.007085,-0.092217,0.014065,-0.166217,-0.008009,0.148194
1679,0.393590,-0.088378,-0.136992,-0.163080,0.101233,0.261111,0.765654,-0.071651,-0.162465,0.264782,...,0.186831,-0.127786,0.096736,-0.142097,-0.008255,-0.093378,0.013021,-0.167352,-0.009074,0.146867
1680,0.393049,-0.086918,-0.134969,-0.161442,0.101075,0.261061,0.764983,-0.071744,-0.161396,0.264589,...,0.186850,-0.127045,0.097826,-0.140977,-0.007621,-0.092686,0.013639,-0.166575,-0.008466,0.146298
1681,0.392771,-0.086712,-0.134765,-0.161248,0.101201,0.261089,0.765165,-0.071357,-0.161430,0.264781,...,0.186858,-0.126812,0.097654,-0.140965,-0.007369,-0.092423,0.013796,-0.166414,-0.008049,0.146415

In [41]:
s=g.T

In [42]:
s[187].values>=0.4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [43]:
#from recom list select highest rated flim which would like by the user .Based on user prediction

highest_rated=[]
input_user_pre=pd.DataFrame(user_pred_Trans[input_user])
input_user_pre=input_user_pre.T
for re in recom:
    value=input_user_pre[re].values
    if(value>=1):
        highest_rated.append(re)

In [44]:
len(highest_rated)

27

In [45]:
# Now we give movieid respective movie list

i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,
encoding='latin-1')

In [46]:
# Creating MovieList based on recom movieid

movie_title=[]
for movieid in highest_rated:
    mov=items[items['movie id']==movieid]['movie title'].values
    movie_title.append(mov)

In [47]:
movie_title

[array(['Seven (Se7en) (1995)'], dtype=object),
 array(['I.Q. (1994)'], dtype=object),
 array(['Santa Clause, The (1994)'], dtype=object),
 array(['Free Willy (1993)'], dtype=object),
 array(['Sleepless in Seattle (1993)'], dtype=object),
 array(['Aladdin (1992)'], dtype=object),
 array(['Dances with Wolves (1990)'], dtype=object),
 array(['Snow White and the Seven Dwarfs (1937)'], dtype=object),
 array(['Spitfire Grill, The (1996)'], dtype=object),
 array(['Private Benjamin (1980)'], dtype=object),
 array(['Empire Strikes Back, The (1980)'], dtype=object),
 array(['Princess Bride, The (1987)'], dtype=object),
 array(['Apocalypse Now (1979)'], dtype=object),
 array(['GoodFellas (1990)'], dtype=object),
 array(['Henry V (1989)'], dtype=object),
 array(['Sting, The (1973)'], dtype=object),
 array(['Unforgiven (1992)'], dtype=object),
 array(['Field of Dreams (1989)'], dtype=object),
 array(['Breaking the Waves (1996)'], dtype=object),
 array(['Men in Black (1997)'], dtype=object),
 array(['Chasing Amy (1997)'], dtype=object),
 array(['Sense and Sensibility (1995)'], dtype=object),
 array(["Marvin's Room (1996)"], dtype=object),
 array(['In & Out (1997)'], dtype=object),
 array(['Client, The (1994)'], dtype=object),
 array(['Aladdin and the King of Thieves (1996)'], dtype=object),
 array(['Some Like It Hot (1959)'], dtype=object)]

In [48]:
# Converting into pure list
movie_title_list=[]
for m in movie_title:
    print(m)
    mv=list(m)
    movie_title_list.append(mv)

['Seven (Se7en) (1995)']
['I.Q. (1994)']
['Santa Clause, The (1994)']
['Free Willy (1993)']
['Sleepless in Seattle (1993)']
['Aladdin (1992)']
['Dances with Wolves (1990)']
['Snow White and the Seven Dwarfs (1937)']
['Spitfire Grill, The (1996)']
['Private Benjamin (1980)']
['Empire Strikes Back, The (1980)']
['Princess Bride, The (1987)']
['Apocalypse Now (1979)']
['GoodFellas (1990)']
['Henry V (1989)']
['Sting, The (1973)']
['Unforgiven (1992)']
['Field of Dreams (1989)']
['Breaking the Waves (1996)']
['Men in Black (1997)']
['Chasing Amy (1997)']
['Sense and Sensibility (1995)']
["Marvin's Room (1996)"]
['In & Out (1997)']
['Client, The (1994)']
['Aladdin and the King of Thieves (1996)']
['Some Like It Hot (1959)']

In [50]:
# Converting into whole list

import itertools
Final_Recommend_movie=list(itertools.chain.from_iterable(movie_title_list))

In [51]:
Final_Recommend_movie

['Seven (Se7en) (1995)',
 'I.Q. (1994)',
 'Santa Clause, The (1994)',
 'Free Willy (1993)',
 'Sleepless in Seattle (1993)',
 'Aladdin (1992)',
 'Dances with Wolves (1990)',
 'Snow White and the Seven Dwarfs (1937)',
 'Spitfire Grill, The (1996)',
 'Private Benjamin (1980)',
 'Empire Strikes Back, The (1980)',
 'Princess Bride, The (1987)',
 'Apocalypse Now (1979)',
 'GoodFellas (1990)',
 'Henry V (1989)',
 'Sting, The (1973)',
 'Unforgiven (1992)',
 'Field of Dreams (1989)',
 'Breaking the Waves (1996)',
 'Men in Black (1997)',
 'Chasing Amy (1997)',
 'Sense and Sensibility (1995)',
 "Marvin's Room (1996)",
 'In & Out (1997)',
 'Client, The (1994)',
 'Aladdin and the King of Thieves (1996)',
 'Some Like It Hot (1959)']

In [52]:
#Checking the Common Movie List

list(set(recom)&set(input_user_watched_movieid))

[]

In [53]:
def userbased(input_user,user_similarity,user_predictions,similar_user_count,thres):
    #Convert the user_sim table into DataFrame
    user_sim_table=pd.DataFrame(user_similarity)
    #Find similarity user for 78 using cosine table
    similar_input_user= user_sim_table[input_user].sort_values(ascending=True).head(similar_user_count).index
    #Convert in to list
    similar_user_input=list(similar_input_user) 
    #Using similar_user_input,can select movie id from ratings table
    similar_user_movieid_list=[]
    for sim_user in similar_user_input:
        sim=list(ratings[ratings['user_id']==sim_user]['movie_id'])
        similar_user_movieid_list.append(sim)
    #Converting as a whole list
    import itertools
    similar_user_movieid_single_list=list(itertools.chain.from_iterable(similar_user_movieid_list))
    #Unique movieid from the list
    Unique_movieid_similar_user=set(similar_user_movieid_single_list)
    #Input user watched movie_list
    input_user_watched_movieid=list(ratings[ratings['user_id']==input_user]['movie_id'].values)
    #Create a list which should have recom movieid to the input user
    recom=[]
    for per_id in Unique_movieid_similar_user:
        if(per_id in input_user_watched_movieid):
            pass
        else:
            recom.append(per_id)
    #From recommendation list selecting only hightest rated(predicted) value
    highest_Rated=[]
    user_pred=pd.DataFrame(user_prediction)
    user_pred_Trans=user_pred.T
    input_user_pre=pd.DataFrame(user_pred_Trans[input_user])
    input_user_pred=input_user_pre.T
    for re in recom:
        value=input_user_pred[re].values
        if(value>=thres):
            highest_Rated.append(re)
    i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
    items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')
    #Creating Movie List based on recom movieid
    movie_title=[]
    for movieid in highest_Rated:
        mov=items[items['movie id']==movieid]['movie title'].values
        movie_title.append(mov)
    #Converting into pure list
    movie_title_list=[]
    for m in movie_title:
        print(m)
        mv=list(m)
        movie_title_list.append(mv)
    #Converting into whole list
    import itertools
    Final_Recommend_movie=list(itertools.chain.from_iterable(movie_title_list))
    print("The common Movie in Recom & User:",list(set(recom)&set(input_user_watched_movieid)))
    return Final_Recommend_movie

In [54]:
#def userbased(input_user,user_similarity,user_predictions,similar_user_count,similar_user_movieid_count,thres):
Recommended_movie=userbased(67,user_similarity,user_pred,5,1.5)

['Professional, The (1994)']
['Dances with Wolves (1990)']
['Snow White and the Seven Dwarfs (1937)']
['Princess Bride, The (1987)']
['Apocalypse Now (1979)']
['Men in Black (1997)']
["Marvin's Room (1996)"]
The common Movie in Recom & User: []