In [1]:
import pandas as pd

In [2]:
stk_data=pd.read_csv('Tatacoffee13_21.csv')

In [3]:
stk_data

            Date     Open     High      Low    Close
0     2013-01-01  1410.60  1427.90  1408.30  1415.10
1     2013-01-02  1421.00  1626.60  1416.15  1607.40
2     2013-01-03  1632.55  1673.90  1613.05  1626.20
3     2013-01-04  1627.75  1627.75  1574.60  1579.05
4     2013-01-07  1580.00  1639.50  1565.50  1595.65
...          ...      ...      ...      ...      ...
2220  2021-12-22   202.90   207.80   201.35   205.00
2221  2021-12-23   206.00   206.85   202.05   202.95
2222  2021-12-24   203.90   203.90   199.35   201.00
2223  2021-12-27   200.00   222.00   196.00   218.35
2224  2021-12-28   219.65   220.45   211.55   212.35

[2225 rows x 5 columns]

In [4]:
stk_data=stk_data[['Open','High','Low','Close']]

In [5]:
stk_data

         Open     High      Low    Close
0     1410.60  1427.90  1408.30  1415.10
1     1421.00  1626.60  1416.15  1607.40
2     1632.55  1673.90  1613.05  1626.20
3     1627.75  1627.75  1574.60  1579.05
4     1580.00  1639.50  1565.50  1595.65
...       ...      ...      ...      ...
2220   202.90   207.80   201.35   205.00
2221   206.00   206.85   202.05   202.95
2222   203.90   203.90   199.35   201.00
2223   200.00   222.00   196.00   218.35
2224   219.65   220.45   211.55   212.35

[2225 rows x 4 columns]

In [6]:
column='Close'

In [7]:
from sklearn.preprocessing import MinMaxScaler
Ms=MinMaxScaler()
data1=Ms.fit_transform(stk_data[[column]])
print('Len : ',data1.shape)

Len :  (2225, 1)

In [8]:
training_size=round(len(data1)*0.80)
print(training_size)
x_train=data1[:training_size]
x_test=data1[training_size:]
print('X_train Length : ',x_train.shape)
print('X_test Length : ',x_test.shape)
y_train=data1[:training_size]
y_test=data1[training_size:]
print('Y_train Length : ',y_train.shape)
print('Y_test Length : ',y_test.shape)

1780
X_train Length :  (1780, 1)
X_test Length :  (445, 1)
Y_train Length :  (1780, 1)
Y_test Length :  (445, 1)

In [9]:
from sklearn.metrics import mean_squared_error
trends=['n','t','c','ct']
lags=[1,2,3,4]
orders=[(1,0,2),(1,0,1),(2,0,1),(1,0,1)]
for i in orders:
    from statsmodels.tsa.arima.model import ARIMA
    model=ARIMA(data1,order=(1,0,0))
    model_fit=model.fit()
    y_pred=model_fit.predict(0,len(data1)-1)
    from ARMIA import sf
    sf.rmsemape(data1,y_pred)

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

RMSE-Testset :  0.01997637686235163
maPe-testset :  3853482698.666795

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

RMSE-Testset :  0.01997637686235163
maPe-testset :  3853482698.666795

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

RMSE-Testset :  0.01997637686235163
maPe-testset :  3853482698.666795
RMSE-Testset :  0.01997637686235163
maPe-testset :  3853482698.666795

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [10]:
forecast=model_fit.predict(len(data1),len(data1)+3)

In [11]:
forecast

array([0.1021397, 0.1023586, 0.1025769, 0.1027946])

In [12]:
from ARMIA import sf
fTestNormTable=sf.conversionSingle(forecast,['closefore'])
forecast_stock_price_test_ori=Ms.inverse_transform(fTestNormTable)
forecast_stock_price_test_oriF=sf.conversionSingle(forecast_stock_price_test_ori,['closefore'])

In [14]:
from ARMIA import sf
sf.graph('Actual','Predicted','TataCoffee - Close - AR -Ori','Days','Price')

TypeError: sf.graph() missing 1 required positional argument: 'ylabel'