In [1]:
import pandas as pd

In [3]:
stk_data=pd.read_csv('Tatacoffee13_21.csv')

In [4]:
stk_data

            Date     Open     High      Low    Close
0     2013-01-01  1410.60  1427.90  1408.30  1415.10
1     2013-01-02  1421.00  1626.60  1416.15  1607.40
2     2013-01-03  1632.55  1673.90  1613.05  1626.20
3     2013-01-04  1627.75  1627.75  1574.60  1579.05
4     2013-01-07  1580.00  1639.50  1565.50  1595.65
...          ...      ...      ...      ...      ...
2220  2021-12-22   202.90   207.80   201.35   205.00
2221  2021-12-23   206.00   206.85   202.05   202.95
2222  2021-12-24   203.90   203.90   199.35   201.00
2223  2021-12-27   200.00   222.00   196.00   218.35
2224  2021-12-28   219.65   220.45   211.55   212.35

[2225 rows x 5 columns]

In [11]:
stk_data=stk_data[['Open','High','Low','Close']]
stk_data

         Open     High      Low    Close
0     1410.60  1427.90  1408.30  1415.10
1     1421.00  1626.60  1416.15  1607.40
2     1632.55  1673.90  1613.05  1626.20
3     1627.75  1627.75  1574.60  1579.05
4     1580.00  1639.50  1565.50  1595.65
...       ...      ...      ...      ...
2220   202.90   207.80   201.35   205.00
2221   206.00   206.85   202.05   202.95
2222   203.90   203.90   199.35   201.00
2223   200.00   222.00   196.00   218.35
2224   219.65   220.45   211.55   212.35

[2225 rows x 4 columns]

In [12]:
column='Close'

In [13]:
from sklearn.preprocessing import MinMaxScaler
Ms=MinMaxScaler()
data1=Ms.fit_transform(stk_data[[column]])
print('Len : ',data1.shape)

Len :  (2225, 1)

In [14]:
training_size=round(len(data1)*0.80)
print(training_size)
x_train=data1[:training_size]
x_test=data1[training_size:]
print('x_train length : ',x_train.shape)
print('y_train length : ',x_test.shape)
y_train=data1[:training_size]
y_test=data1[training_size:]
print('y_train Length :',y_train.shape)
print('y_test Length : ',y_test.shape)

1780
x_train length :  (1780, 1)
y_train length :  (445, 1)
y_train Length : (1780, 1)
y_test Length :  (445, 1)

In [18]:
order=[(1,1,1),(1,1,2),(2,3,1),(2,2,2)]
for i in order:
    from statsmodels.tsa.arima.model import ARIMA
    model=ARIMA(data1,order=i)
    model_fit=model.fit()
    y_pred=model_fit.predict(0,len(data1)-1)
    from ARIMA import sf
    sf.rmsemape(data1,y_pred)

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

RMSE-Testset :  0.02288594565997708
maPe-testset :  2377525502.6204567

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

RMSE-Testset :  0.022885202880894368
maPe-testset :  2415748899.181892

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

RMSE-Testset :  0.028981848198880382
maPe-testset :  1584632346.4024582
RMSE-Testset :  0.02388943374866075
maPe-testset :  1716369021.1985087

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [19]:
forecast=model_fit.predict(len(data1),len(data1)+3)

In [20]:
forecast

array([0.10165549, 0.10154115, 0.10144976, 0.10134454])

In [21]:
from ARIMA import sf
fTestNormTable=sf.conversionSingle(forecast,['closefore'])
forecast_stock_price_test_ori=Ms.inverse_transform(fTestNormTable)
forecast_stock_price_test_oriF=sf.conversionSingle(forecast_stock_price_test_ori,['closefore'])

In [22]:
forecast_stock_price_test_oriF

    closefore
0  211.926793
1  211.743996
2  211.597876
3  211.429644