In [1]:
import pandas as pd
import datetime as dt

In [9]:
stk_data=pd.read_csv('Tatacoffee13_21.csv')

In [10]:
stk_data

            Date     Open     High      Low    Close
0     2013-01-01  1410.60  1427.90  1408.30  1415.10
1     2013-01-02  1421.00  1626.60  1416.15  1607.40
2     2013-01-03  1632.55  1673.90  1613.05  1626.20
3     2013-01-04  1627.75  1627.75  1574.60  1579.05
4     2013-01-07  1580.00  1639.50  1565.50  1595.65
...          ...      ...      ...      ...      ...
2220  2021-12-22   202.90   207.80   201.35   205.00
2221  2021-12-23   206.00   206.85   202.05   202.95
2222  2021-12-24   203.90   203.90   199.35   201.00
2223  2021-12-27   200.00   222.00   196.00   218.35
2224  2021-12-28   219.65   220.45   211.55   212.35

[2225 rows x 5 columns]

In [11]:
stk_data['Date']=pd.to_datetime(stk_data['Date'])

In [12]:
stk_data=stk_data[
    (stk_data['Date']>=pd.Timestamp('2020-01-01')) &
    (stk_data['Date']<=pd.Timestamp('2021-12-31'))
]

In [13]:
stk_data

           Date    Open    High     Low   Close
1728 2020-01-01   92.50   92.70   91.30   91.50
1729 2020-01-02   91.90   93.25   91.55   92.45
1730 2020-01-03   92.70   96.20   92.50   93.90
1731 2020-01-06   92.75   93.25   90.10   90.35
1732 2020-01-07   91.05   92.55   90.50   91.55
...         ...     ...     ...     ...     ...
2220 2021-12-22  202.90  207.80  201.35  205.00
2221 2021-12-23  206.00  206.85  202.05  202.95
2222 2021-12-24  203.90  203.90  199.35  201.00
2223 2021-12-27  200.00  222.00  196.00  218.35
2224 2021-12-28  219.65  220.45  211.55  212.35

[497 rows x 5 columns]

In [14]:
#To Pick a particular Column (Use[[]])
stk_data=stk_data[['Open','High','Low','Close']]

In [15]:
stk_data

        Open    High     Low   Close
1728   92.50   92.70   91.30   91.50
1729   91.90   93.25   91.55   92.45
1730   92.70   96.20   92.50   93.90
1731   92.75   93.25   90.10   90.35
1732   91.05   92.55   90.50   91.55
...      ...     ...     ...     ...
2220  202.90  207.80  201.35  205.00
2221  206.00  206.85  202.05  202.95
2222  203.90  203.90  199.35  201.00
2223  200.00  222.00  196.00  218.35
2224  219.65  220.45  211.55  212.35

[497 rows x 4 columns]

In [17]:
column="Close"

In [18]:
"""Time Series is a Univarinate , We are able to create a model for that one particular column (Date--> in the dataset is the TImeSeries data
    close-->Timeseries data,Open,High,Low)"""

'Time Series is a Univarinate , We are able to create a model for that one particular column (Date--> in the dataset is the TImeSeries data\n    close-->Timeseries data,Open,High,Low)'

In [19]:
from sklearn.preprocessing import MinMaxScaler
Ms=MinMaxScaler()
data1=Ms.fit_transform(stk_data[[column]])
print('Len : ',data1.shape)

Len :  (497, 1)

In [20]:
# In TimeSeries Analysis we need a Standardsation or to Normalaisation we gonna use MinMaxScaler

In [22]:
#Training and Testset Data
training_size=round(len(data1)*0.80)
print(training_size)
x_train=data1[:training_size]
x_test=data1[training_size:]
print('X_Train Length : ',x_train.shape)
print('X_Test Length : ',x_test.shape)
y_train=data1[:training_size]
y_test=data1[training_size:]
print('y_train Length : ',y_train.shape)
print('y_test length : ',y_test.shape)

398
X_Train Length :  (398, 1)
X_Test Length :  (99, 1)
y_train Length :  (398, 1)
y_test length :  (99, 1)

In [26]:
from sklearn.metrics import mean_squared_error
trends=['n','t','c','ct']
orders=[(0,0,1),(0,0,2)]
from statsmodels.tsa.arima.model import ARIMA
for td in trends:
    model=ARIMA(x_train,order=(0,0,10),trend=td)
    model_fit=model.fit()
    y_pred=model_fit.predict(len(x_train),len(data1)-1)

    from sklearn.metrics import r2_score
    mse=mean_squared_error(y_test,y_pred,squared=False)
    from MovingAverage import sf
    print('Trend={}'.format(td))
    sf.rmsemape(y_test,y_pred)
    print('**************')

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'

Trend=n
RMSE-Testset :  0.8379791126424845
maPe-testset :  0.9487856084630277
**************

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'

Trend=t
RMSE-Testset :  0.12269017470955386
maPe-testset :  0.12237544548221649
**************

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'

Trend=c
RMSE-Testset :  0.5102575713299403
maPe-testset :  0.575449170535172
**************
Trend=ct
RMSE-Testset :  0.1802417384296685
maPe-testset :  0.19360324951588356
**************

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [28]:
#Forecasting
forecast=model_fit.predict(len(data1),len(data1)+3)

In [29]:
forecast

array([0.74873853, 0.75008601, 0.75143349, 0.75278097])

In [31]:
#Changing those numbers into original values
from MovingAverage import sf
fTestNormTable=sf.conversionSingle(forecast,['Closefore'])
forecast_stock_price_test_ori=Ms.inverse_transform(fTestNormTable)
forecast_stock_price_test_oriF=sf.conversionSingle(forecast_stock_price_test_ori,['closefore'])

In [32]:
forecast_stock_price_test_oriF

    closefore
0  188.964861
1  189.216032
2  189.467203
3  189.718373